<?xml version="1.0" encoding="utf-8"?><Database Name="Hospital" Class="AppointmentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-MATTHIE\SQLEXPRESS;Initial Catalog=Hospital;Integrated Security=True" SettingsObjectName="Assigment2.Properties.Settings" SettingsPropertyName="HospitalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Appointment" Member="Appointment">
    <Type Name="Appointment">
      <Column Name="AppointmentCode" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AppointmentDate" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AppointmentTime" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DoctorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>