<?xml version="1.0" encoding="utf-8"?><Database Name="Hospital" Class="PatientDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-MATTHIE\SQLEXPRESS;Initial Catalog=Hospital;Integrated Security=True" SettingsObjectName="Assigment2.Properties.Settings" SettingsPropertyName="HospitalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Patient" Member="Patient">
    <Type Name="Patient">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PatientAdress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PatientGender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>